backend:
  name: github
  repo: hermannsblum/simon-site
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://entengruetze.com
  site_domain: https://entengruetze.com
  auth_endpoint: /api/auth
media_folder: static/img
public_folder: /img
collections:
  - name: disney
    label: Disney
    label_singular: 'Disney'
    folder: content/disney
    create: true
    # adding a nested object will show the collection folder structure
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
      - label: Cover
        name: cover
        widget: image
      - label: Comic Pages
        name: comic_pages
        widget: list
        fields:
          - { label: Page, name: page, widget: image }
