backend:
  name: github
  repo: hermannsblum/simon-site
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://entengruetze.com
  site_domain: https://entengruetze.com
  auth_endpoint: /api/auth
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
